#ifndef COMPUTE_TILE_CONSTANTS_H
#define COMPUTE_TILE_CONSTANTS_H

#define NUM_PIXELS_PER_GROUP_X  8
#define NUM_PIXELS_PER_GROUP_Y  8
#define TOTAL_PIXELS_PER_GROUP  (NUM_PIXELS_PER_GROUP_X * NUM_PIXELS_PER_GROUP_Y)

#endif // COMPUTE_TILE_CONSTANTS_H